title: liminal
author: Anson
description: Drifting through the adult world and documenting my experiences

url: "https://ansonnchan.github.io"
baseurl: "/chanblogs"

theme: minima

plugins:
  - jekyll-sitemap

minima:
  show_feed: false
  social_links:
    github: ansonnchan
    linkedin: ansonnchan

permalink: /:title/
