title: liminal
author: Anson

url: "https://ansonnchan.github.io"
baseurl: "/chanblogs"

theme: minima

plugins:
  - jekyll-sitemap

github_username: ansonnchan
linkedin_username: ansonnchan

permalink: /:title/

paginate: 10 

minima:
  show_feed: false 


